/* The editor's service worker, as source.
   ---------------------------------------------------------------------------
   Generated rather than shipped as a file, because what it owns depends on the
   site: `build.format` decides whether the editor answers at `/edit` or at
   `/edit.html`, and a worker that named the wrong one would cache nothing on a
   third of the fleet while reporting perfect health.

   ⚠ This file's product is a **string**, which puts it in the one file class
   that has already caused a silent production failure here. The console's own
   worker carried a bolded path in its header comment; the markdown way of
   writing one puts a star immediately before a slash; that sequence closes a
   block comment; the script threw at the next word and never registered, and
   nothing said so because a failed registration is caught on purpose. Nothing
   in an Astro build ever parses a generated script, so the guard is a test —
   `worker.test.ts` compiles this output with `new Function`, which parses
   without running. Keep it that way, and keep stars away from slashes.

   ── What it may cache, which is the part that is not the console's ─────────
   The console reasoned that root scope was harmless because no visitor ever
   reaches /admin. That is still true of the editor. What is *not* true of the
   editor is the other half: a client site's origin also serves the client's
   actual site, and the owner is the person most likely to look at it — right
   after saving a change to it.

   So the fetch handler is a strict passthrough for everything it does not own,
   and what it owns is deliberately tiny:

     the editor page   the one route this worker exists for
     /_astro/          content-addressed by filename, so a cached copy and a
                       fresh copy are the same bytes by construction
     the manifest      and nothing beside it

   The public site's HTML is **not** on that list and must never be. An owner
   who saves a sentence and then opens their own page has to see the new
   sentence; a cache they cannot see and did not ask for, serving them
   yesterday's copy of their own work, would be a worse failure than having no
   offline mode at all. The API is not on the list either, for the reason the
   console gave: a stale fleet number on screen with no way for the page to
   know it is stale. The editor keeps its own drafts and knows their age.

   Passthrough means returning without calling `respondWith`, which hands the
   request back to the network untouched — not fetching and forwarding, which
   would look identical and would put every one of the owner's page loads
   through a worker that could fail. */

export interface WorkerSourceOptions {
  /** The editor's route, as injected — "/edit". Both it and its `.html` twin
      are owned, because the site's `build.format` decides which one exists and
      a worker cannot see that config. */
  editorPath: string;
  /** Where the manifest answers. */
  manifestPath: string;
  /** Bumped by every kit release, so an owner's device drops the previous
      shell instead of serving it forever. */
  version: string;
}

export function serviceWorkerSource(options: WorkerSourceOptions): string {
  const editor = options.editorPath.replace(/\/+$/, "") || "/edit";
  const shell = JSON.stringify([editor, options.manifestPath]);
  const cache = JSON.stringify(`sk-editor-${options.version}`);
  const editorJson = JSON.stringify(editor);
  const manifestJson = JSON.stringify(options.manifestPath);

  /* Written as a template rather than assembled from fragments so the whole
     script is readable here in the shape it will have on disk. */
  return `/* The editor's offline shell. Generated by @shaahink/sitekit — do not edit.
   Owns the editor route and its content-addressed bundle, and passes
   everything else straight through to the network untouched. The site's own
   pages are deliberately not cached: an owner who has just saved must see
   what they saved. */

const CACHE = ${cache};
const EDITOR = ${editorJson};
const MANIFEST = ${manifestJson};
const SHELL = ${shell};

self.addEventListener("install", (event) => {
  /* A failed precache must not fail the install: the worker is still useful
     for the runtime caching below, and refusing to install because one asset
     404'd is how a site ends up with no offline mode at all. */
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(SHELL))
      .catch(() => undefined)
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)))
      )
      .then(() => self.clients.claim())
  );
});

function owns(path) {
  if (path === EDITOR || path === EDITOR + "/" || path === EDITOR + ".html") return true;
  if (path === MANIFEST) return true;
  return path.indexOf("/_astro/") === 0;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (!owns(url.pathname)) return;

  /* The editor page: network first, so a signed-in reload is always the real
     thing, and the cache is only ever the answer to "the train went into a
     tunnel". */
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(EDITOR, copy));
          return response;
        })
        .catch(() => caches.match(EDITOR).then((held) => held || Response.error()))
    );
    return;
  }

  /* Everything else here is content-addressed by filename, so what is held is
     what would be fetched. Serve it and refresh behind the reader. */
  event.respondWith(
    caches.match(request).then((held) => {
      const fresh = fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => held || Response.error());
      return held || fresh;
    })
  );
});
`;
}
