/* The dual header emitter.
   ---------------------------------------------------------------------------
   One definition of a site's headers, emitted as both vercel.json and
   Cloudflare _headers/_redirects, so no host-specific file is ever
   hand-maintained and the host stays a choice (PLAN §3.4).

   Paths are written in the neutral (Cloudflare-shaped) form: "/*" matches
   everything, "/api/*" a prefix, "/favicon.svg" exactly. The Vercel emitter
   translates them to its regex form. */

export interface HeaderRule {
  /** "/*", "/api/*", or an exact path. */
  path: string;
  /** Header name → value, emitted in insertion order. */
  headers: Record<string, string>;
}

export interface RedirectRule {
  from: string;
  to: string;
  /** HTTP status. Default 302. */
  status?: number;
}

export interface HostConfig {
  headers: HeaderRule[];
  /** Branches whose pushes must never deploy — the screenshot branch. This is
      a Vercel-file concern; Cloudflare Pages configures it in the dashboard. */
  disableDeploymentsFor?: string[];
  redirects?: RedirectRule[];
  /** Extra top-level vercel.json keys — framework, outputDirectory — merged in
      directly after $schema. A Vercel-file concern with no Cloudflare
      counterpart; the Cloudflare emitters never see it. */
  vercel?: Record<string, unknown>;
}

/** The complete vercel.json text, trailing newline included — meant to be
    written to disk verbatim and committed. */
export function vercelJson(config: HostConfig): string {
  const out: Record<string, unknown> = {
    "$schema": "https://openapi.vercel.sh/vercel.json",
    ...config.vercel
  };

  if (config.disableDeploymentsFor && config.disableDeploymentsFor.length) {
    const branches: Record<string, boolean> = {};
    for (const branch of config.disableDeploymentsFor) branches[branch] = false;
    out["git"] = { deploymentEnabled: branches };
  }

  out["headers"] = config.headers.map((rule) => ({
    source: vercelSource(rule.path),
    headers: Object.entries(rule.headers).map(([key, value]) => ({ key, value }))
  }));

  if (config.redirects && config.redirects.length) {
    for (const rule of config.redirects) refuseUntranslatable(rule);
    out["redirects"] = config.redirects.map((rule) => ({
      source: vercelSource(rule.from),
      destination: rule.to,
      permanent: rule.status === 301 || rule.status === 308
    }));
  }

  /* House format: standard two-space JSON, except each header pair sits on
     one line — the shape session 1 wrote by hand, which this emitter has to
     reproduce byte-for-byte before it may replace those files. */
  const text = JSON.stringify(out, null, 2).replace(
    /\{\n\s+"key": (".*"),\n\s+"value": (".*")\n\s+\}/g,
    '{ "key": $1, "value": $2 }'
  );
  return text + "\n";
}

/** The complete Cloudflare _headers text. */
export function cloudflareHeaders(config: HostConfig): string {
  return config.headers
    .map((rule) =>
      [rule.path, ...Object.entries(rule.headers).map(([key, value]) => `  ${key}: ${value}`)].join("\n")
    )
    .join("\n\n") + "\n";
}

/** The complete Cloudflare _redirects text. */
export function cloudflareRedirects(config: HostConfig): string {
  const rules = config.redirects || [];
  return rules.map((rule) => `${rule.from} ${rule.to} ${rule.status ?? 302}`).join("\n") + "\n";
}

/** The complete `functions/_middleware.js` source — the same header rules,
    applied to the responses `_headers` does not reach. */
export function cloudflareMiddleware(config: HostConfig): string {
  /* JSON.stringify rather than hand-built literals: a header value is content
     and can carry a quote or a backslash — a CSP does — and this is the one
     place in the kit that writes JavaScript for somebody else to run. */
  const rules = JSON.stringify(config.headers, null, 2);

  return `/* Generated by sitekit-headers --cloudflare from headers.config.mjs. Do not edit.
   ---------------------------------------------------------------------------
   Cloudflare Pages applies _headers to static assets and **not** to anything a
   Function returns; Vercel applies vercel.json's rules to both. Measured on
   2026-07-29 against the live sk-works, which sends all five security headers
   on /api/feedback, and against a local Pages build, which sent none until a
   file like this one existed. Session 9.5 Task 3, finding 1.

   That gap is silent — the site looks right, the pages carry their headers,
   _headers parses without complaint, and only the API responses are bare. So
   the whole point of one neutral definition per site fails on the half of the
   traffic nobody curls. This file closes it from the same config, which is why
   it is generated: the hand-written version that proved the finding restated
   the /* rule by hand, and a hand-maintained host file is what the emitter
   exists to abolish.

   Root middleware runs for every request, static assets included, so the rules
   are applied by matching the request path the way _headers matches it —
   in file order, later rule wins, exactly as one definition should behave on
   either host. A response is rebuilt rather than mutated because a Function's
   headers are immutable once it has constructed them, and left untouched when
   no rule matches. */

const RULES = ${rules};

/* "/*" matches everything, "/api/*" a prefix, anything else exactly — the
   _headers semantics, not a router's. */
function matches(pattern, path) {
  if (!pattern.endsWith("/*")) return path === pattern;
  return path.startsWith(pattern.slice(0, -1));
}

export async function onRequest(context) {
  const response = await context.next();
  const path = new URL(context.request.url).pathname;

  const applicable = RULES.filter((rule) => matches(rule.path, path));
  if (!applicable.length) return response;

  const headers = new Headers(response.headers);
  for (const rule of applicable) {
    for (const [key, value] of Object.entries(rule.headers)) headers.set(key, value);
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
}
`;
}

/* "/api/*" → "/api/(.*)", "/*" → "/(.*)", exact paths pass through. */
function vercelSource(path: string): string {
  if (path.endsWith("/*")) return path.slice(0, -2) + "/(.*)";
  return path;
}

/* Cloudflare's destination placeholders: ":splat" for whatever a "*" matched,
   and ":name" for a named segment. A host:port or a scheme cannot be mistaken
   for one — the character after the colon must begin an identifier. */
const PLACEHOLDER = /:([A-Za-z_][A-Za-z0-9_]*)/g;

function placeholders(path: string): string[] {
  return Array.from(new Set(Array.from(path.matchAll(PLACEHOLDER), (match) => match[1] as string)));
}

/* Refuse a redirect whose destination Vercel would emit verbatim.
   ---------------------------------------------------------------------------
   The neutral form is Cloudflare-shaped, and only the *source* is translated:
   "/old/* → /new/:splat" is right on Cloudflare and, through vercelJson, gives
   source "/old/(.*)" with the destination passed through — where ":splat" is
   not a token Vercel knows, so it lands on a literal "/new/:splat". The file
   emits, the schema validates, and the redirect is wrong. Session 9.5 Task 3
   finding 7 measured exactly that.

   A placeholder the *source* declares is fine on both hosts, because Vercel's
   path-to-regexp reads ":year" in a source the same way Cloudflare does. What
   cannot be translated is a placeholder with nothing to bind to — ":splat"
   always, since the wildcard source becomes the unnamed capture "/(.*)" and
   Vercel destinations can only name parameters.

   Refusing rather than guessing at a translation is the checkAnnotations()
   precedent: fail the build instead of emitting something that will not work.
   It is also the lesson of the Cloudflare emitters themselves, which shipped
   in 0.2.0 and were never once invoked until 9.5 called them and found this.
   An untested translation would repeat that. Whoever writes the fleet's first
   wildcard redirect can prove one against a real deployment and teach it here. */
function refuseUntranslatable(rule: RedirectRule): void {
  const declared = new Set(placeholders(rule.from));
  const orphans = placeholders(rule.to).filter((name) => !declared.has(name));
  if (!orphans.length) return;

  const names = orphans.map((name) => `":${name}"`).join(", ");
  throw new Error(
    `redirect "${rule.from} → ${rule.to}" cannot be emitted for Vercel: ${names} ` +
      `${orphans.length === 1 ? "is a placeholder" : "are placeholders"} the source does not declare, ` +
      `so Vercel would redirect to that text literally.` +
      (orphans.includes("splat")
        ? ` ":splat" has no Vercel spelling at all — "${rule.from}" becomes the unnamed capture ` +
          `"${vercelSource(rule.from)}", and a Vercel destination can only reference a named parameter.`
        : "") +
      ` Send it to a fixed path, which both hosts honour, or keep the wildcard and maintain the rule ` +
      `per host — and prove any translation against a real deployment, because a redirect that emits ` +
      `cleanly and does not redirect is what this refusal exists to prevent.`
  );
}
